package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

var completionsHelp = cmdHelp{
	Usage: "ws completions <bash|zsh|fish|install|uninstall>",
	Subcommands: []string{
		"  bash         Print bash completion script",
		"  zsh          Print zsh completion script",
		"  fish         Print fish completion script",
		"  install      Add completion to shell rc file (~/.bashrc, ~/.zshrc, or fish config)",
		"  uninstall    Remove completion from shell rc file",
	},
	Flags: []string{
		"      --shell string   Override shell detection for install/uninstall (bash|zsh|fish)",
		"      --dry-run        Preview changes without writing (default: false)",
	},
}

// Sentinel markers for idempotent install/uninstall.
const (
	completionMarkerStart = "# >>> ws shell completion >>>"
	completionMarkerEnd   = "# <<< ws shell completion <<<"
)

func runCompletions(args []string, globals globalFlags, stdin io.Reader, stdout, stderr io.Writer) int {
	if hasHelpArg(args) {
		return printCmdHelp(stdout, completionsHelp)
	}

	if len(args) == 0 {
		return printUsageError(stderr, completionsHelp)
	}

	action := strings.ToLower(strings.TrimSpace(args[0]))

	switch action {
	case "bash", "zsh", "fish":
		script := completionScript(action)
		if globals.json {
			return writeJSON(stdout, stderr, "completions", map[string]any{
				"shell":  action,
				"script": script,
			})
		}
		fmt.Fprintln(stdout, script)
		return 0
	case "install":
		return runCompletionsInstall(args[1:], globals, stdin, stdout, stderr)
	case "uninstall":
		return runCompletionsUninstall(args[1:], globals, stdin, stdout, stderr)
	default:
		fmt.Fprintf(stderr, "unsupported shell: %s\n", action)
		return 1
	}
}

// ── Shell scripts (thin __complete dispatchers) ────────────────────

func completionScript(shell string) string {
	switch shell {
	case "bash":
		return bashCompletionScript()
	case "zsh":
		return zshCompletionScript()
	case "fish":
		return fishCompletionScript()
	default:
		return ""
	}
}

func bashCompletionScript() string {
	return `# ws bash completion — generated by ws completions bash
_ws_completions() {
    local IFS=$'\n'
    local out line directive
    local -a comps=()

    # Call the binary to resolve completions for the current word list.
    out=$(ws __complete "${COMP_WORDS[@]:1}" 2>/dev/null)

    # Parse output: each line is a completion, last line is :<directive>.
    while IFS= read -r line; do
        if [[ "$line" == :* ]]; then
            directive="${line#:}"
        else
            [[ -n "$line" ]] && comps+=("$line")
        fi
    done <<< "$out"

    # If no explicit completions and directive allows files, let bash
    # fall through to default file completion.
    if (( ${#comps[@]} == 0 )); then
        if (( directive & 4 )); then
            # NoFileComp — nothing to offer.
            COMPREPLY=()
        fi
        return 0
    fi

    COMPREPLY=("${comps[@]}")

    # Apply directives.
    if (( directive & 2 )); then
        compopt -o nospace
    fi
    if (( directive & 4 )); then
        compopt +o default
    fi

    return 0
}
complete -o default -F _ws_completions ws`
}

func zshCompletionScript() string {
	return `#compdef ws
# ws zsh completion — generated by ws completions zsh

_ws() {
    local -a completions
    local directive line

    # Build the word list from the current command line.
    # words[1] is "ws", words[2..] are the arguments.
    local -a ws_args=("${words[@]:1}")

    # Call the binary.
    local out
    out=$(ws __complete "${ws_args[@]}" 2>/dev/null)

    # Parse output.
    while IFS= read -r line; do
        if [[ "$line" == :* ]]; then
            directive="${line#:}"
        else
            [[ -n "$line" ]] && completions+=("$line")
        fi
    done <<< "$out"

    if (( ${#completions[@]} == 0 )); then
        if (( directive & 4 )); then
            _message 'no completions'
        else
            _files
        fi
        return
    fi

    compadd -- "${completions[@]}"

    # NoSpace
    if (( directive & 2 )); then
        compstate[insert]=unambiguous
    fi
}

compdef _ws ws`
}

func fishCompletionScript() string {
	return `# ws fish completion — generated by ws completions fish

function __ws_complete
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)

    # Drop the command name "ws".
    set -e tokens[1]

    set -l out (ws __complete $tokens $current 2>/dev/null)

    # Last line is :<directive>.
    set -l directive 0
    for line in $out
        if string match -qr '^:[0-9]+$' -- $line
            set directive (string sub -s 2 -- $line)
        else
            echo $line
        end
    end

    # Return 1 if NoFileComp so fish does not add file completions.
    if test (math "$directive & 4") -ne 0
        return 1
    end
    return 0
end

complete -c ws -f -a '(__ws_complete)'`
}

// ── Install / Uninstall ────────────────────────────────────────────

func runCompletionsInstall(args []string, globals globalFlags, stdin io.Reader, stdout, stderr io.Writer) int {
	shell, dryRun, err := parseCompletionFlags(args, globals)
	if err != nil {
		fmt.Fprintln(stderr, err.Error())
		return 1
	}

	rcPath, evalLine, err := completionRCInfo(shell)
	if err != nil {
		fmt.Fprintln(stderr, err.Error())
		return 1
	}

	// Read existing rc file.
	content, _ := os.ReadFile(rcPath) // missing file is fine — we'll create it

	// Check for sentinel markers.
	if containsCompletionMarker(string(content)) {
		fmt.Fprintf(textOut(globals, stdout), "Completion already installed in %s — nothing to do.\n", rcPath)
		if globals.json {
			return writeJSON(stdout, stderr, "completions.install", map[string]any{
				"shell": shell, "path": rcPath, "action": "already_installed",
			})
		}
		return 0
	}

	// Check for pre-existing non-sentinel ws completion lines and remove them.
	cleaned := removeStaleCompletionLines(string(content))

	// Build the block to append.
	block := fmt.Sprintf("\n%s\n%s\n%s\n", completionMarkerStart, evalLine, completionMarkerEnd)
	newContent := cleaned + block

	if dryRun {
		globals.dryRun = true
	}

	plan := Plan{Command: "completions.install"}
	plan.Actions = append(plan.Actions, Action{
		ID:          "completions-install",
		Description: fmt.Sprintf("Install ws completion into %s", rcPath),
		Execute: func() error {
			if err := os.MkdirAll(filepath.Dir(rcPath), 0o755); err != nil {
				return err
			}
			return os.WriteFile(rcPath, []byte(newContent), 0o644)
		},
	})

	planResult := RunPlan(plan, stdin, stdout, globals)

	if globals.json {
		action := "installed"
		if globals.dryRun {
			action = "dry_run"
		}
		return writeJSON(stdout, stderr, "completions.install", map[string]any{
			"shell":   shell,
			"path":    rcPath,
			"action":  action,
			"block":   block,
			"actions": planResult.Actions,
		})
	}

	if planResult.WasExecuted("completions-install") {
		out := textOut(globals, stdout)
		fmt.Fprintf(out, "Completion installed in %s\n", rcPath)
		fmt.Fprintf(out, "Run `source %s` or open a new terminal to activate.\n", rcPath)
	}
	return planResult.ExitCode()
}

func runCompletionsUninstall(args []string, globals globalFlags, stdin io.Reader, stdout, stderr io.Writer) int {
	shell, dryRun, err := parseCompletionFlags(args, globals)
	if err != nil {
		fmt.Fprintln(stderr, err.Error())
		return 1
	}

	rcPath, _, err := completionRCInfo(shell)
	if err != nil {
		fmt.Fprintln(stderr, err.Error())
		return 1
	}

	content, err := os.ReadFile(rcPath)
	if err != nil {
		fmt.Fprintf(textOut(globals, stdout), "No rc file at %s — nothing to remove.\n", rcPath)
		if globals.json {
			return writeJSON(stdout, stderr, "completions.uninstall", map[string]any{
				"shell": shell, "path": rcPath, "action": "not_found",
			})
		}
		return 0
	}

	if !containsCompletionMarker(string(content)) {
		fmt.Fprintf(textOut(globals, stdout), "No ws completion block found in %s — nothing to remove.\n", rcPath)
		if globals.json {
			return writeJSON(stdout, stderr, "completions.uninstall", map[string]any{
				"shell": shell, "path": rcPath, "action": "not_installed",
			})
		}
		return 0
	}

	cleaned := removeMarkerBlock(string(content))

	if dryRun {
		globals.dryRun = true
	}

	plan := Plan{Command: "completions.uninstall"}
	plan.Actions = append(plan.Actions, Action{
		ID:          "completions-uninstall",
		Description: fmt.Sprintf("Remove ws completion from %s", rcPath),
		Execute: func() error {
			return os.WriteFile(rcPath, []byte(cleaned), 0o644)
		},
	})

	planResult := RunPlan(plan, stdin, stdout, globals)

	if globals.json {
		action := "removed"
		if globals.dryRun {
			action = "dry_run"
		}
		return writeJSON(stdout, stderr, "completions.uninstall", map[string]any{
			"shell":   shell,
			"path":    rcPath,
			"action":  action,
			"actions": planResult.Actions,
		})
	}

	if planResult.WasExecuted("completions-uninstall") {
		fmt.Fprintf(textOut(globals, stdout), "Completion removed from %s\n", rcPath)
	}
	return planResult.ExitCode()
}

// ── Helpers ────────────────────────────────────────────────────────

// parseCompletionFlags extracts --shell and --dry-run from install/uninstall args.
func parseCompletionFlags(args []string, globals globalFlags) (shell string, dryRun bool, err error) {
	dryRun = globals.dryRun
	for i := 0; i < len(args); i++ {
		a := args[i]
		if strings.HasPrefix(a, "--shell=") {
			shell = strings.ToLower(strings.TrimSpace(strings.TrimPrefix(a, "--shell=")))
			continue
		}
		switch a {
		case "--shell":
			if i+1 >= len(args) {
				return "", false, fmt.Errorf("--shell requires a value")
			}
			i++
			shell = strings.ToLower(strings.TrimSpace(args[i]))
		case "--dry-run":
			dryRun = true
		}
	}
	if shell == "" {
		shell = detectShell()
	}
	if shell != "bash" && shell != "zsh" && shell != "fish" {
		return "", false, fmt.Errorf("unsupported shell %q (use --shell bash|zsh|fish)", shell)
	}
	return shell, dryRun, nil
}

// detectShell resolves the current shell from $SHELL.
func detectShell() string {
	s := os.Getenv("SHELL")
	if s == "" {
		return "bash" // safe default on Linux
	}
	base := filepath.Base(s)
	switch base {
	case "bash", "zsh", "fish":
		return base
	default:
		return base
	}
}

// completionRCInfo returns the rc file path and the eval line for a given shell.
func completionRCInfo(shell string) (rcPath, evalLine string, err error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", "", err
	}
	switch shell {
	case "bash":
		return filepath.Join(home, ".bashrc"), `eval "$(ws completions bash)"`, nil
	case "zsh":
		return filepath.Join(home, ".zshrc"), `eval "$(ws completions zsh)"`, nil
	case "fish":
		confDir := os.Getenv("XDG_CONFIG_HOME")
		if confDir == "" {
			confDir = filepath.Join(home, ".config")
		}
		return filepath.Join(confDir, "fish", "conf.d", "ws.fish"), "ws completions fish | source", nil
	default:
		return "", "", fmt.Errorf("unsupported shell: %s", shell)
	}
}

// containsCompletionMarker returns true if the text contains our sentinel markers.
func containsCompletionMarker(text string) bool {
	return strings.Contains(text, completionMarkerStart)
}

// removeMarkerBlock removes everything between (and including) the sentinel
// markers. Preserves the rest of the file exactly.
func removeMarkerBlock(text string) string {
	start := strings.Index(text, completionMarkerStart)
	if start < 0 {
		return text
	}
	end := strings.Index(text, completionMarkerEnd)
	if end < 0 {
		return text
	}
	end += len(completionMarkerEnd)
	// Also consume the trailing newline after the end marker.
	if end < len(text) && text[end] == '\n' {
		end++
	}
	// Also consume a leading newline before the start marker.
	if start > 0 && text[start-1] == '\n' {
		start--
	}
	return text[:start] + text[end:]
}

// removeStaleCompletionLines removes any pre-existing ws completion lines
// that were manually added before the sentinel system existed.
// This handles the duplicate-entry problem.
func removeStaleCompletionLines(text string) string {
	lines := strings.Split(text, "\n")
	var cleaned []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if isStaleCompletionLine(trimmed) {
			continue
		}
		cleaned = append(cleaned, line)
	}
	return strings.Join(cleaned, "\n")
}

// isStaleCompletionLine detects old-style manual completion setup lines.
func isStaleCompletionLine(line string) bool {
	// Common patterns people might have added manually:
	//   eval "$(ws completions bash)"
	//   source <(ws completions bash)
	//   ws completions bash | source
	if strings.Contains(line, "ws completions") || strings.Contains(line, "ws-completions") {
		// Don't match comment lines (they're harmless).
		if strings.HasPrefix(line, "#") {
			return false
		}
		return true
	}
	return false
}
