package ignore

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestUserRulesLoadSaveRoundTrip(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "ws", "ignore.json")

	rules := DefaultUserRules()
	rules.Exclude = append(rules.Exclude, RuleEntry{Pattern: "datasets/", Note: "too large"})
	rules.SafeHarbors = append(rules.SafeHarbors, RuleEntry{Pattern: "Backups/**"})
	rules.SuppressDefaults = append(rules.SuppressDefaults, "*.log")

	if err := SaveUserRules(path, rules); err != nil {
		t.Fatalf("save failed: %v", err)
	}

	loaded, err := LoadUserRules(path)
	if err != nil {
		t.Fatalf("load failed: %v", err)
	}

	if len(loaded.Exclude) != 1 || loaded.Exclude[0].Pattern != "datasets/" {
		t.Fatalf("expected exclude datasets/, got %+v", loaded.Exclude)
	}
	if len(loaded.SafeHarbors) != 1 || loaded.SafeHarbors[0].Pattern != "Backups/**" {
		t.Fatalf("expected harbor Backups/**, got %+v", loaded.SafeHarbors)
	}
	if len(loaded.SuppressDefaults) != 1 || loaded.SuppressDefaults[0] != "*.log" {
		t.Fatalf("expected suppress *.log, got %+v", loaded.SuppressDefaults)
	}
}

func TestLoadUserRulesMissingFileReturnsDefault(t *testing.T) {
	rules, err := LoadUserRules("/nonexistent/ignore.json")
	if err != nil {
		t.Fatalf("expected default on missing file, got error: %v", err)
	}
	if rules.Schema != UserRulesSchema {
		t.Fatalf("expected schema %d, got %d", UserRulesSchema, rules.Schema)
	}
	if len(rules.Exclude) != 0 {
		t.Fatalf("expected empty exclude, got %+v", rules.Exclude)
	}
}

func TestBuildEngineWithDefaults(t *testing.T) {
	engine := BuildEngine(DefaultUserRules())

	// Hidden files should be excluded by default rule -:.*
	res := engine.Evaluate(".git/config", false)
	if res.Included {
		t.Fatal("expected .git/config to be excluded by defaults")
	}

	// ws/ paths that would otherwise be excluded should be safe harbors
	// ws/ws-log/session.log would be excluded by -g:*.log but re-included by +g:ws/**
	res = engine.Evaluate("ws/ws-log/session.log", false)
	if !res.Included {
		t.Fatal("expected ws/ws-log/session.log to be included (safe harbor)")
	}
	if !res.SafeHarbor {
		t.Fatal("expected SafeHarbor=true for ws/ws-log/session.log")
	}

	// ws/ paths not excluded by any rule are just included (not safe harbor)
	res = engine.Evaluate("ws/config.json", false)
	if !res.Included {
		t.Fatal("expected ws/config.json to be included")
	}

	// Normal file should be included
	res = engine.Evaluate("README.md", false)
	if !res.Included {
		t.Fatal("expected README.md to be included")
	}
}

func TestBuildEngineUserExclude(t *testing.T) {
	rules := DefaultUserRules()
	rules.Exclude = append(rules.Exclude, RuleEntry{Pattern: "datasets/"})

	engine := BuildEngine(rules)

	res := engine.Evaluate("datasets/big.csv", false)
	if res.Included {
		t.Fatal("expected datasets/big.csv to be excluded by user rule")
	}
}

func TestBuildEngineSuppressDefault(t *testing.T) {
	rules := DefaultUserRules()
	rules.SuppressDefaults = append(rules.SuppressDefaults, "*.log")

	engine := BuildEngine(rules)

	// *.log should now be included (default suppressed)
	res := engine.Evaluate("app.log", false)
	if !res.Included {
		t.Fatalf("expected app.log to be included after suppressing *.log default, got rule=%s", res.Rule)
	}
}

func TestBuildEngineUserSafeHarbor(t *testing.T) {
	rules := DefaultUserRules()
	rules.SafeHarbors = append(rules.SafeHarbors, RuleEntry{Pattern: "Backups/**"})

	engine := BuildEngine(rules)

	// Backups/ content should be included via safe harbor override
	res := engine.Evaluate("Backups/backup.tar.gz", false)
	if !res.Included {
		t.Fatal("expected Backups/backup.tar.gz to be included via user safe harbor")
	}
	if !res.SafeHarbor {
		t.Fatal("expected SafeHarbor=true for Backups/backup.tar.gz")
	}
}

func TestBuildEngineSuppressHarbor(t *testing.T) {
	// ws/ harbor cannot be added as user safe harbor — rejected at API level.
	_, err := AddUserSafeHarbor("/tmp/fake-ignore.json", "ws/**", "")
	if err == nil {
		t.Fatal("expected error when trying to add ws/ as user safe harbor")
	}
}

func TestGenerateMegaignore(t *testing.T) {
	rules := DefaultUserRules()
	rules.Exclude = append(rules.Exclude, RuleEntry{Pattern: "datasets/", Note: "too large"})
	rules.SafeHarbors = append(rules.SafeHarbors, RuleEntry{Pattern: "Backups/**"})

	content := GenerateMegaignore(rules)

	if !strings.Contains(content, "# Generated by ws") {
		t.Fatal("expected generated header")
	}
	if !strings.Contains(content, "-:datasets/") {
		t.Fatal("expected user exclude rule in output")
	}
	if !strings.Contains(content, "+g:Backups/**") {
		t.Fatal("expected user safe harbor in output")
	}
	if !strings.Contains(content, "-s:*") {
		t.Fatal("expected sentinel at end")
	}
	if !strings.Contains(content, "-:.*") {
		t.Fatal("expected default exclude rules")
	}
	if !strings.Contains(content, "+:ws") {
		t.Fatal("expected default safe harbor")
	}
}

func TestAddUserExcludeDeduplicate(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "ws", "ignore.json")

	if err := SaveUserRules(path, DefaultUserRules()); err != nil {
		t.Fatal(err)
	}

	ok1, err := AddUserExclude(path, "big.bin", "")
	if err != nil {
		t.Fatal(err)
	}
	if !ok1 {
		t.Fatal("expected first add to succeed")
	}

	ok2, err := AddUserExclude(path, "big.bin", "")
	if err != nil {
		t.Fatal(err)
	}
	if ok2 {
		t.Fatal("expected duplicate add to return false")
	}
}

func TestWriteMegaignore(t *testing.T) {
	tmp := t.TempDir()
	megaPath := filepath.Join(tmp, ".megaignore")

	rules := DefaultUserRules()
	rules.Exclude = append(rules.Exclude, RuleEntry{Pattern: "test/"})

	if err := WriteMegaignore(megaPath, rules); err != nil {
		t.Fatal(err)
	}

	content, err := os.ReadFile(megaPath)
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(string(content), "-:test/") {
		t.Fatalf("expected -:test/ in megaignore, got:\n%s", string(content))
	}
}

func TestGetRuleStats(t *testing.T) {
	rules := DefaultUserRules()
	rules.Exclude = append(rules.Exclude, RuleEntry{Pattern: "a"}, RuleEntry{Pattern: "b"})
	rules.SafeHarbors = append(rules.SafeHarbors, RuleEntry{Pattern: "Backups/**"})
	rules.SuppressDefaults = append(rules.SuppressDefaults, "*.log")

	stats := GetRuleStats(rules)
	if stats.UserExclude != 2 {
		t.Fatalf("expected 2 user excludes, got %d", stats.UserExclude)
	}
	if stats.UserHarbors != 1 {
		t.Fatalf("expected 1 user harbor, got %d", stats.UserHarbors)
	}
	if stats.SuppressedDefaults != 1 {
		t.Fatalf("expected 1 suppressed default, got %d", stats.SuppressedDefaults)
	}
}
